package com.expedia.adaptivealerting.modelservice.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;
import org.springframework.data.elasticsearch.annotations.Query;

import java.util.UUID;

@Document(indexName = "detectors_mappings", type = "details", createIndex = true)
@Data
public class DetectorMappingDto {
    @Id
    public String id;//id will be generated by framework

    private User aa_user;
    private DetectorConsumerMapping aa_detector;

    @Data
    public static class User {
        private String id;
    }

    private boolean aa_enabled;
    private long aa_lastModifiedTime;
    private long aa_createdTime;

    @Field(type = FieldType.Object)
    private String aa_query;


    @Data
    public static class DetectorConsumerMapping {
        private String consumerId;

        @JsonFormat(shape = JsonFormat.Shape.STRING)
        private UUID uuid;
    }
}



